CREATE TABLE Owner (ownerId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, addressId integer(10) NOT NULL, name varchar(50), surname varchar(50), company varchar(50) NOT NULL, FOREIGN KEY(addressId) REFERENCES Address(addressId));
CREATE TABLE Address (addressId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, street varchar(50) NOT NULL, streetNumber integer(10) NOT NULL, postalCode varchar(10) NOT NULL, city varchar(30) NOT NULL, country varchar(50) NOT NULL);
CREATE TABLE Hotel (hotelId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, ownerId integer(10) NOT NULL, addressId integer(10) NOT NULL, name varchar(50) NOT NULL, stars integer(1), type varchar(30) NOT NULL, isAccessible blob, numberRooms integer(5) NOT NULL, numberFloors integer(5) NOT NULL, constructionYear integer(4) NOT NULL, capacity integer(4) NOT NULL, employees integer(10) NOT NULL, operatingMode varchar(20) NOT NULL, FOREIGN KEY(ownerId) REFERENCES Owner(ownerId), FOREIGN KEY(addressId) REFERENCES Address(addressId));
CREATE TABLE Client (clientId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, addressId integer(10) NOT NULL, name varchar(50) NOT NULL, surname varchar(50) NOT NULL, phoneNumber varchar(20) NOT NULL, email varchar(100) NOT NULL, additionalInfo varchar(255), FOREIGN KEY(addressId) REFERENCES Address(addressId));
CREATE TABLE Room (roomId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, hotelId integer(10) NOT NULL, roomNumber integer(10) NOT NULL, floor integer(10) NOT NULL, type varchar(50) NOT NULL, isAccessible blob, hasBalcony blob, capacity integer(2) NOT NULL, pricePerNight numeric(10, 2) NOT NULL, description varchar(255), FOREIGN KEY(hotelId) REFERENCES Hotel(hotelId));
CREATE TABLE Feature (featureId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, type varchar(50));
CREATE TABLE PensionType (pensionTypeId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, type varchar(50) NOT NULL);
CREATE TABLE Booking (bookingId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, clientId integer(10) NOT NULL, startDate date NOT NULL, endDate date NOT NULL, bookingDate date NOT NULL, hasBeenCanceled blob NOT NULL, FOREIGN KEY(clientId) REFERENCES Client(clientId));
CREATE TABLE Bill (billId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, paymentId integer(10) NOT NULL, bookingId integer(10) NOT NULL, "date" date NOT NULL, currency varchar(5) NOT NULL, amount numeric(10, 2) NOT NULL, isPaid blob NOT NULL, FOREIGN KEY(bookingId) REFERENCES Booking(bookingId), FOREIGN KEY(paymentId) REFERENCES Payment(paymentId));
CREATE TABLE Payment (paymentId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, method varchar(20) NOT NULL);
CREATE TABLE BillArticles (articleId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, description varchar(20) NOT NULL, amount numeric(10, 2) NOT NULL);
CREATE TABLE Room_Booking (roomId integer(10) NOT NULL, bookingId integer(10) NOT NULL, PRIMARY KEY (roomId, bookingId), FOREIGN KEY(roomId) REFERENCES Room(roomId), FOREIGN KEY(bookingId) REFERENCES Booking(bookingId));
CREATE TABLE Room_Feature (roomId integer(10) NOT NULL, featureId integer(10) NOT NULL, PRIMARY KEY (roomId), FOREIGN KEY(roomId) REFERENCES Room(roomId), FOREIGN KEY(featureId) REFERENCES Feature(featureId));
CREATE TABLE Bill_BillArticles (billId integer(10) NOT NULL, articleId integer(10) NOT NULL, PRIMARY KEY (billId, articleId), FOREIGN KEY(billId) REFERENCES Bill(billId), FOREIGN KEY(articleId) REFERENCES BillArticles(articleId));
CREATE TABLE Hotel_PensionType (HotelhotelId integer(10) NOT NULL, pensionTypeId integer(10) NOT NULL, PRIMARY KEY (HotelhotelId, pensionTypeId), FOREIGN KEY(HotelhotelId) REFERENCES Hotel(hotelId), FOREIGN KEY(pensionTypeId) REFERENCES PensionType(pensionTypeId));
CREATE UNIQUE INDEX Owner_ownerId ON Owner (ownerId);
CREATE UNIQUE INDEX Address_addressId ON Address (addressId);
CREATE UNIQUE INDEX Hotel_hotelId ON Hotel (hotelId);
CREATE UNIQUE INDEX Client_clientId ON Client (clientId);
CREATE UNIQUE INDEX Room_roomId ON Room (roomId);
CREATE UNIQUE INDEX Feature_featureId ON Feature (featureId);
CREATE UNIQUE INDEX PensionType_pensionTypeId ON PensionType (pensionTypeId);
CREATE UNIQUE INDEX Booking_bookingId ON Booking (bookingId);
CREATE UNIQUE INDEX Bill_billId ON Bill (billId);
CREATE UNIQUE INDEX Payment_paymentId ON Payment (paymentId);
CREATE UNIQUE INDEX BillArticles_articleId ON BillArticles (articleId);
INSERT INTO Address(addressId, street, streetNumber, postalCode, city, country) VALUES (1, 'Bahnhofstrasse', 23, '4109', 'Zürich', 'Schweiz');
INSERT INTO Address(addressId, street, streetNumber, postalCode, city, country) VALUES (2, 'Amselstrasse', 3, '8903', 'Olten', 'Schweiz');
INSERT INTO Owner(ownerId, addressId, name, surname, company) VALUES (1, 1, 'Alex', 'Suter', 'Blackrock AG');
INSERT INTO Hotel(hotelId, ownerId, addressId, name, stars, type, isAccessible, numberRooms, numberFloors, constructionYear, capacity, employees, operatingMode) VALUES (1, 1, 2, 'Alpenblick', 4, 'Hotel', 1, 50, 4, 1990, 100, 40, 'Ganzjährig');
INSERT INTO Client(clientId, addressId, name, surname, phoneNumber, email, additionalInfo) VALUES (1, 2, 'Bastian', 'Bueeler', '0763967873', 'bastian.bueeler@gmail.com', 'Bester Kunde');
INSERT INTO Room(roomId, hotelId, roomNumber, floor, type, isAccessible, hasBalcony, capacity, pricePerNight, description) VALUES (1, 1, 101, 1, 'EZ', 0, 1, 1, 100, 'Einzelzimmer mit Balkon und Bergblick');
INSERT INTO Feature(featureId, type) VALUES (1, 'Bett');
INSERT INTO Feature(featureId, type) VALUES (2, 'Wlan');
INSERT INTO Feature(featureId, type) VALUES (3, 'Badewanne');
INSERT INTO PensionType(pensionTypeId, type) VALUES (1, 'Vollpension');
INSERT INTO Booking(bookingId, clientId, startDate, endDate, bookingDate, hasBeenCanceled) VALUES (1, 1, '01.01.2024', '09.01.2024', '03.06.2023', 0);
INSERT INTO Payment(paymentId, method) VALUES (1, 'Kreditkarte');
INSERT INTO Payment(paymentId, method) VALUES (2, 'Twint');
INSERT INTO Payment(paymentId, method) VALUES (3, 'Rechnung');
INSERT INTO Payment(paymentId, method) VALUES (4, 'Paypal');
INSERT INTO Payment(paymentId, method) VALUES (5, 'Amex');
INSERT INTO Payment(paymentId, method) VALUES (6, 'Bar');
INSERT INTO Bill(billId, paymentId, bookingId, "date", currency, amount, isPaid) VALUES (1, 1, 1, '09.01.2024', 'CHF', 800, 1);
INSERT INTO BillArticles(articleId, description, amount) VALUES (1, 'Ski Pass', 200);
INSERT INTO BillArticles(articleId, description, amount) VALUES (2, 'Getränk', 10);
INSERT INTO BillArticles(articleId, description, amount) VALUES (3, 'Tresor', 30);
INSERT INTO Room_Booking(roomId, bookingId) VALUES (1, 1);
INSERT INTO Room_Feature(roomId, featureId) VALUES (1, 1);
INSERT INTO Room_Feature(roomId, featureId) VALUES (1, 2);
INSERT INTO Bill_BillArticles(billId, articleId) VALUES (1, 1);
INSERT INTO Hotel_PensionType(HotelhotelId, pensionTypeId) VALUES (1, 1);
